### PR TITLE
add gwizard-metrics and gwizard-services

### PR DESCRIPTION
**Pull request by stevesea**

### CODE REVIEW

**Comment by stickfigure** [comment]
I added a commit to the PR to fix a few minor things (project is tabs not spaces, some pom issues). I'm actually not quite sure what happens when I commit to your PR and how that gets back into this project. Does it need to be resubmitted?

I would love to have that PR on a branch so that I can experiment with making Guava Services a bit more "guicy". Is that possible? It doesn't look like I can change the branch here. Thanks!

**Comment by stevesea** [comment]
I'm not sure either. This is my first time working with github.

I won't be offended at all if you reject the PR. I can fix up the whitespace issues on my end and move the revisions onto a branch and resubmit.

**Comment by stickfigure** [comment]
I think you have much of it already committed to a branch 'pr/1' in your repository. Maybe this is as easy as (in your repo), creating a branch, then merging 'pr/1' into that branch, then creating a new pull request based on that branch. That will pick up my changes.

**Comment by stickfigure** [comment]
I figured out how to merge this into my own branch so I'm working off of that. I'll push it to a 'services' branch. In the mean time this PR has done its work. Thanks!

**Pull request closed without merging**
